baseURL: "https://saeedmehrang.github.io/"
title: &title Saeed Mehrang
defaultContentLanguage: en
languages:
  en:
    languageCode: "en-us"
    languageName: "English"
    weight: 1

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
        #   weight: 5
        - name: Papers
          url: papers/
          weight: 2
        # - name: Courses
        #   url: courses/
        #   weight: 3
        - name: Blogs
          url: blogs/
          weight: 4
        # - name: Data
        #   url: data/
        #   weight: 5
        # - name: News
        #   url: news/
        # weight: 6
        - name: Tags
          url: tags/
          weight: 7
        - name: Archive
          url: archive/
          weight: 1
        

params:
    description: "This website hosts Saeed Mehrang's research papers, curriculum vitae, and contact information."
    author: *title
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers"] # ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Saeed Mehrang
          subtitle: |
                    I genuinely care about living humbly. It's important to me that we protect our planet, 
                    respect everyone's freedom to choose, and compassionately support the less fortunate. 
                    I truly believe that education is the key to overcoming poverty. We live only once, so 
                    let's be happy and responsible toward creating a peaceful life for ourselves and the rest 
                    of the beings in this world. It is truly a responsibility of all of us to care for each other. 
                    It's crucial that we use our financial resources wisely (as every amount matters) to create
                    a sustainable living and cultivate fairness in and across our communities.

                    I am a Lead Data Scientist and Founding Partner at Vaalia Health, Helsini, Finland.
                    I hold Doctor of Science (DSc) degree in Information and Communication Technologies
                    from University of Turku.  

                    I have worked on various AI based technologies covering
                    various kinds of neural network based models for the analysis of text, image, audio, 
                    biosignals, and tabular data. My current focus is on time series analysis, causal AI, 
                    and applications of Agentic workflows for patient-care optimization. Previously, 
                    I was a Senior AI Scientist at Silo AI.
                    
                    See more about my skills and expertise in my CV by clicking the CV button below.
                    
          imageUrl: "my-image.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Courses
            #   url: courses/
            - name: Blogs
              url: blogs/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            # - name: News
            #   url: news/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: saeedmehrang@gmail.com
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://scholar.google.fi/citations?user=1q3dgpEAAAAJ&hl=fi
        - name: GitHub
          url: https://github.com/saeedmehrang
        - name: Linkedin
          url: https://fi.linkedin.com/in/saeedmehrang
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        # - name: Twitter
        #   url: https://x.com/pmichaillat
        # - name: Bluesky
        #   url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: Home
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

module:
    imports:
        - path: github.com/adityatelange/hugo-PaperMod
